server:
  port: 8088 #ovveride in second instance with 8089
  servlet:
    session:
      cookie:
        same-site: lax
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/jwt
    username: jwt
    password: jwt
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
pl.marcinzygmunt:
  jwt:
    jwtCookieName: jwt
    jwtCookiePath: /api
    refreshCookieName: refresh-token
    refreshCookiePath: /api/auth/refreshtoken
    cookieValidSec: 24 * 60 * 60
    cookieHttp: true
    cookieSecure: true
    secret: B374A26A71490437AA024E4FADD5B497FDFF1A8EA6FF12F6FB65AF2720B59CCF
    expirationMin: 30
    refreshExpirationMin: 30
    refreshCache: refreshTokens
  hazelcast:
    members: 127.0.0.1:5701, 127.0.0.1:5702
    cluster-name: jwt-hazelcast-cache
    port: 5701 #ovveride in second instance with 5702
    public-ip-address: 127.0.0.1
    maps:
      - name: refresh_token
        time-to-live: 30m
        max-idle: 15m
      - name: sessions
        time-to-live: 30m
        max-idle: 30m
  default-user:
    create: true
    overrideUser: true
    email: admin@marcinzygmunt.pl
    password: password

