server:
  port: ${APPLICATION_PORT:8088}
  servlet:
    session:
      cookie:
        same-site: lax
spring:
  datasource:
    url:  ${DATABASE_URL:jdbc:postgresql://localhost:5432/jwt}
    username: ${BE_DB_USER:jwt}
    password: ${BE_DB_PASS:jwt}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
pl.marcinzygmunt:
  jwt:
    jwtCookieName: jwt
    jwtCookiePath: /api
    refreshCookieName: refresh-token
    refreshCookiePath: /api/auth/refreshtoken
    cookieValidSec: 24 * 60 * 60
    cookieHttp: true
    cookieSecure: true
    secret: B374A26A71490437AA024E4FADD5B497FDFF1A8EA6FF12F6FB65AF2720B59CCF
    expirationMin: 30
    refreshExpirationMin: 30
    refreshCache: refreshTokens
  hazelcast:
    members:
    cluster-name: jwt-hazelcast-cache
    port: 5701
    public-ip-address: 127.0.0.1
    maps:
      - name: refresh_token
        time-to-live: 30m
        max-idle: 15m
      - name: sessions
        time-to-live: 30m
        max-idle: 30m
  default-user:
    create: true
    overrideUser: true
    email: admin@marcinzygmunt.pl
    password: password

